fix(dracut): move hooks directory from /usr/lib to /var/lib
dracut-ng/dracut-ng pull request #114
Opened 2024-04-06 12:30 UTC by dracutng

## Changes

Since https://github.com/systemd/systemd/commit/ffc1ec73, /usr is mounted as read-only in the initramfs by default.

Fixes https://github.com/dracutdevs/dracut/issues/2588

2024-04-06 20:23 UTC, freswa commented
It's just a feeling, but `/var/lib` is a directory which is used to store data and managed by the software itself.
Hook dirs imho belong to either `/usr` when another package provides them, or `/etc` if the administrator/user would like to create them.

Just my 2 cents :)

2024-04-07 00:52 UTC, bdrung commented
I agree with @fre

2024-04-07 00:55 UTC, bdrung requested changes
I agree with @freswa, the hooks should live in `/usr` and or `/etc`. Generating dynamic configuration should be better placed in `/run` instead.

2024-04-10 13:32 UTC, aafeijoo-suse commented
You can read the old discussion which led us to choose `/var` as the "least bad option" here: https://bugzilla.opensuse.org/show_bug.cgi?id=1218068

2024-04-10 18:51 UTC, Conan-Kudo requested changes
I am not sure this is a good change on its own. This will break backwards compatibility for anyone already using the existing hooks directory for packaged hooks, and the new path doesn't work on systems where `/var` is not available during transactions (e.g. RPM-OSTree).

2024-04-11 06:31 UTC, aafeijoo-suse commented
> I am not sure this is a good change on its own. This will break backwards compatibility for anyone already using the existing hooks directory for packaged hooks,

There is a compat symlink to the old location.

https://github.com/dracut-ng/dracut-ng/pull/114/files#diff-1a92fcdd8eaf1d31c9913c0e2f96022f82331a5ba7a2d89802927bae30484d1eR51

`/usr` is read-only in systemd git main, so a change is required.

> and the new path doesn't work on systems where `/var` is not available during transactions (e.g. RPM-OSTree).

I you follow the discussion in https://bugzilla.opensuse.org/show_bug.cgi?id=1218068 and https://github.com/dracutdevs/dracut/pull/2591, I initially suggested a directory like `/.dracut`, but we were trying to guess if `/var` could be used without breaking anything.

2024-04-15 14:45 UTC, pvalena commented
> > There is a compat symlink to the old location.
> 
> One option - that I am more and more considering - is to only add the compat symlink and do not change the documentation. This would make the compat symlink an implementation detail and we would still recommend out of tree dracut modules to use e.g. /usr/lib instead of /var/lib .
> 
> Any thoughts on this ?

Just to be clear, that would mean 2 locations:
 -  (1) for user-created (packaged) hooks; and
 -  (2) for runtime-created (generated) hooks

Those need to be then handled both - e.g. by copying all of the (1) to (2) prior to generating new ones. I'm fine with `/var` but IMHO if done correctly, we could use:
 - `/usr/lib` for (1)
 - `/run/dracut` for (2)

Is there some reason for not doing this? Is there some reason for not using `/run` that I've missed?

2024-04-15 21:32 UTC, pvalena commented
> ```
>     # symlink to old hooks location for compatibility
>     ln_r /var/lib/dracut/hooks /lib/dracut/hooks
> ```
> 
> takes care about both cases already (assuming /var is writable).

Hmm I didn't realize this before, but now seeing it, I think it doesn't work in case there're some pre-existing files in `/lib/dracut/hooks`.

The original intent is to create a symlink `/lib/dracut/hooks` (to pointing to directory `/var/lib/dracut/hooks`), which is fine, but if there already is a directory `/lib/dracut/hooks`, then it will create a symlink **in** that directory instead (creating symlink `/lib/dracut/hooks/hooks`; [test log](https://gist.github.com/pvalena/f1e87e58913dc2c6d8948b442be6b023)).

2024-04-16 07:23 UTC, aafeijoo-suse commented
> > ```
> >     # symlink to old hooks location for compatibility
> >     ln_r /var/lib/dracut/hooks /lib/dracut/hooks
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > takes care about both cases already (assuming /var is writable).
> 
> Hmm I didn't realize this before, but now seeing it, I think it doesn't work in case there're some pre-existing files in `/lib/dracut/hooks`.
> 
> The original intent is to create a symlink `/lib/dracut/hooks` (to pointing to directory `/var/lib/dracut/hooks`), which is fine, but if there already is a directory `/lib/dracut/hooks` (empyty or not), then it will create a symlink **in** that directory instead (creating symlink `/lib/dracut/hooks/hooks`; [test log](https://gist.github.com/pvalena/f1e87e58913dc2c6d8948b442be6b023)).

FTR, we have been using the current proposal since systemd introduced the change, otherwise Tumbleweed with systemd from git main would not work. So, it works. That said, I think your idea of copying the hooks to /run at boot may also be valid, I could give it a try (maybe on a separate PR) if that's the desired path to follow.

2024-04-16 12:40 UTC, lnykryn commented
This is probably a stupid idea, but shouldn't we just set ProtectSystem=no for the hooks unit files? I understand the reasoning behind the systemd change. If you build initrd with let's say mkosi-initrd you mostly don't need to touch /usr. But Dracut is unfortunately built in a way where it does a lot of "self-modifications" (I mean scripts that generate scripts....)

2024-04-17 11:44 UTC, Conan-Kudo commented
I'm closing this as #186 was merged.

2024-04-17 11:44 UTC, closed without merging

2024-04-17 11:56 UTC, aafeijoo-suse commented
> I'm closing this as #186 was merged.

That's a "good" way to end an ongoing discussion.

2024-04-26 23:04 UTC, AdamWill commented
I think it'd be reasonable to re-open this, as #186 / #194 is really more of a band-aid than a long term "fix". It does seem like it would be much cleaner in the long term to really change dracut's own idea of where the hooks go, not just kinda trick it with a symlink. But it's also clearly more disruptive.