feat(systemd-bsod): dracut module for systemd-bsod
dracut-ng/dracut-ng pull request #175
Opened 2024-04-14 18:22 UTC by LaszloGombos

## Changes

Include https://www.freedesktop.org/software/systemd/man/latest/systemd-bsod.service.html

bsod depends on qrencode. Add qrencode to Arch and Fedora container to trigger testing.

While at it add astyle, jq to the Fedora container as well as it was missing for testing some of the dracut modules.

## Checklist
- [ ] I have tested it locally
- [ ] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

2024-04-15 06:32 UTC, aafeijoo-suse requested changes
> ## Checklist
> 
>     * [x]  I have tested it locally

This cannot work without adding the binary executed by the new service and its required libraries.

I would also make this optional, creating a new module only for this or adding it to the systemd-journald module.

2024-04-15 13:12 UTC, aafeijoo-suse requested changes

2024-04-15 13:12 UTC, aafeijoo-suse commented on modules.d/01systemd-bsod/module-setup.sh
> +        "$systemdsystemunitdir"/sysinit.target.wants/systemd-bsod.service \
`s/sysinit.target.wants/initrd.target.wants/`

2024-04-15 13:12 UTC, aafeijoo-suse commented on modules.d/01systemd-bsod/module-setup.sh
> +        qrencode
`systemd-bsod` does not require or use the `qrencode` binary, it calls `libqrencode` via dlopen, so you should add it with `inst_libdir_file`.

2024-04-15 13:12 UTC, aafeijoo-suse commented on modules.d/01systemd-bsod/module-setup.sh
> +    echo systemd
`systemd-bsod.service` is just continuously watching the journal, even its source code is [on the same level of hierarchy](https://github.com/systemd/systemd/tree/main/src/journal), so it should depend only on `systemd-journald`.

We should start actually using the available 01systemd modules in dracut and break out the 00systemd monster. Maybe I submit a PR with that.

2024-04-15 15:10 UTC, aafeijoo-suse approved these changes
Module working as expected.

2024-04-20 18:18 UTC, Conan-Kudo approved these changes

2024-04-20 18:19 UTC, merged