feat(sh): meta package for improved shell selection
dracut-ng/dracut-ng pull request #527
Opened 2024-07-20 22:42 UTC by LaszloGombos

## Changes

cherry-pick from https://github.com/dracutdevs/dracut/pull/2564

## Checklist
- [ ] I have tested it locally
- [ ] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

Fixes #522

2024-07-21 13:01 UTC, Conan-Kudo requested changes
I think this is reasonable, but I don't think we should call this `sh`. Instead, it should be called `shell-interpreter`, since this governs the interpreter used for dracut.

2024-07-21 13:01 UTC, Conan-Kudo commented on modules.d/00sh/module-setup.sh
> +    shells='dash bash busybox'
I would prefer `bash` to be the most preferred option, followed by `dash` and then `busybox`.

2024-07-21 15:38 UTC, Conan-Kudo approved these changes

2024-07-21 15:38 UTC, merged

2024-07-22 09:57 UTC, aafeijoo-suse reviewed
This PR was merged very quickly... I don't want to hurt any feelings so, just 2 remarks about 3975e26a84cd8645b15d0a863263a63da93650e0:
- What happens if `busybox` is compiled without setting `CONFIG_FEATURE_INSTALLER`?
- But the worst part is... where do you think `busybox` is effectively running `--install`? I'll give you a hint, see what the `ln_r` code does:

https://github.com/dracut-ng/dracut-ng/blob/381be95f1511b7d311f99b7c6cdcbf37084601e1/dracut-init.sh#L1093