test: do not force no-hostonly for all test runs
dracut-ng/dracut-ng pull request #545
Opened 2024-07-25 19:03 UTC by LaszloGombos

## Changes

- test: do not force no-hostonly for all test runs
Different distributions and containers might prefer different defaults.
The motivation of this work is to increase test coverage and to run the tests in the same configurations as dracut is used.

## Checklist
- [ ] I have tested it locally
- [ ] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

Fixes #

2024-07-25 22:59 UTC, LaszloGombos commented
The log confirms that for Fedora tests are running in hostonly

```
dracut[W]: Running in hostonly mode in a container!
```

2024-07-26 22:43 UTC, Conan-Kudo approved these changes

2024-07-26 22:44 UTC, Conan-Kudo requested changes
This looks good in principle, though I'm concerned about the failing tests...

2024-07-26 22:45 UTC, LaszloGombos commented
tests are failing because the changes in the CI container will only take effect after PR is landed and not during the PR run.

2024-07-26 22:46 UTC, Conan-Kudo approved these changes
YOLO

2024-07-26 22:46 UTC, merged