fix(dracut-functions.sh): skip dir in get_persistent_dev()
dracut-ng/dracut-ng pull request #559
Opened 2024-07-30 05:46 UTC by pfliu

I observed the following directory layout under /dev/disk/by-path:

/dev/disk/by-path/
├── pci-0000:00:07.0 -> ../../vda
├── pci-0000:00:07.0-part
│   ├── by-partnum
│   │   ├── 1 -> ../../../../vda1
│   │   ├── 2 -> ../../../../vda2
│   │   └── 3 -> ../../../../vda3
│   ├── by-partuuid
│   │   ├── 102645f0-b6a7-47d5-93ae-60bd063ecbc5 -> ../../../../vda1 │   │   ├── 32dc3e8a-70cb-4afb-8642-d4f2e0a92941 -> ../../../../vda3 │   │   └── 46beb739-55c1-4746-ab90-b329a0c82ea5 -> ../../../../vda2 │   └── by-uuid
│       └── 11ea5cf3-7132-40d4-a114-a8d76edca51f -> ../../../../vda2
├── pci-0000:00:07.0-part1 -> ../../vda1
├── pci-0000:00:07.0-part2 -> ../../vda2
├── pci-0000:00:07.0-part3 -> ../../vda3
├── virtio-pci-0000:00:07.0 -> ../../vda
├── virtio-pci-0000:00:07.0-part1 -> ../../vda1
├── virtio-pci-0000:00:07.0-part2 -> ../../vda2
└── virtio-pci-0000:00:07.0-part3 -> ../../vda3

As showed above, 'pci-0000:00:07.0-part' is a directory, so get_maj_min() returns '0:0' for it.

This will raise an issue in the case that kdump dumps the vmcore through nfs. In that case, no block device is passed to
get_persistent_dev(), so _dev=$(get_maj_min "$1") also equals '0:0'. Finally, it wrongly fits into the match:
        if [ "$_tmp" = "$_dev" ]; then
            printf -- "%s" "$i"
            return
        fi

And kdump kernel boots up and wait for 'pci-0000:00:07.0-part' indefinitely.

This pull request changes...

## Changes

## Checklist
- [ ] I have tested it locally
- [ ] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

Fixes #

2024-07-31 15:47 UTC, jozzsi commented
https://github.com/dracutdevs/dracut/pull/2668#issuecomment-2258275654 suggests that this PR is no longer needed as the issue does not exists any more in this repository. @pfliu can you please confirm ?

2024-08-01 05:48 UTC, pfliu commented
> PR is no longer needed as the issue does not exists any

IIUC, you mentioned about 18abcc53 fix(dracut.sh): do not add device if `find_block_device` returns an error

But later, it is reverted by:
commit 0885d6b2bb9d449f8a4e4f89ded3b619338df28d
Author: Laszlo Gombos <laszlo.gombos@gmail.com>
Date:   Sun Apr 7 09:38:00 2024 -0400

    revert: "fix(dracut.sh): do not add device if find_block_device returns"
    
    This reverts commit 3d0d7e0737bd80f522f19918dc052bd795548b5e.

diff --git a/dracut.sh b/dracut.sh
index 18033a19..a0af3dd2 100755
--- a/dracut.sh
+++ b/dracut.sh
@@ -1667,7 +1667,7 @@ if [[ $hostonly ]] && [[ $hostonly_default_device != "no" ]]; then
         "/boot/zipl"; do
         mp=$(readlink -f "$dracutsysrootdir$mp")
         mountpoint "$mp" > /dev/null 2>&1 || continue
-        _dev=$(find_block_device "$mp") || continue
+        _dev=$(find_block_device "$mp")
         _bdev=$(readlink -f "/dev/block/$_dev")
         [[ -b $_bdev ]] && _dev=$_bdev
         [[ $mp == "/" ]] && root_devs+=("$_dev")


dracut-ng in centos stream-10 is based on dracut-ng 101, which includes both commits.  So the problem is persistent.

Thanks,
Pingfan

2024-08-06 09:25 UTC, pfliu commented
@pvalena , could you share your opinion?

Thanks

2024-08-06 12:09 UTC, pvalena commented
Well, this not only skips directories, it also skips symlinks (which is unwanted), as `-f` tests for regular files only.  If we just want to avoid directories, we could instead add one line:
```bash
        [[ -d $i ]] && continue
```

2024-08-06 12:36 UTC, LaszloGombos requested changes
https://github.com/dracut-ng/dracut-ng/pull/565 is a safer alternative of this PR.

2024-08-10 00:18 UTC, closed without merging