fix(systemd): Add base as dependency
dracut-ng/dracut-ng pull request #570
Opened 2024-08-08 16:33 UTC by PrincessDoreena

For systemd to run properly inside initramfs, /etc/initrd-release is required to exist. [1] 
/etc/initrd-release is only written in the base module.

[1]: https://systemd.io/INITRD_INTERFACE/#using-systemd-inside-an-initrd

This pull request changes...

## Changes
Dependencies of the `systemd` module

## Checklist
- [ x ] I have tested it locally
- [ x ] I have reviewed and updated any documentation if relevant
- [ x ] I am providing new code and test(s) for it

2024-08-08 19:13 UTC, jozzsi commented
I think we should take a closer look of which of the many`*systemd*` modules should add the base module dependency. Not only `systemd` module but also the `systemd-initrd` and `dracut-systemd` modules are good candidates for adding the base dependency.

This PR break 6 tests as it seems the meaning of `systemd` dracut module is also used to build not only initrd's but also rootfs (without `/etc/initrd-release` file).

Based on this observations, I think it is better to add the `base` dependency to the `systemd-initrd` - which is a module specific to build initrds.

Hopefully moving this change to `systemd-initrd` from `systemd` will fix the CI failures as well.

2024-08-18 15:41 UTC, LaszloGombos requested changes
This change should be in the `systemd-initrd` module.

2024-08-18 15:41 UTC, LaszloGombos commented on modules.d/00systemd/module-setup.sh
> +    echo base
@PrincessDoreena the suggestion from @jozzsi makes sense for me. This change should be in the `systemd-initrd` dracut module instead. Would you be able to make this change in this PR or should someone else take it over from here ?

2024-08-19 22:35 UTC, PrincessDoreena commented
I will try fixing it today.

Laszlo Gombos ***@***.***> ezt írta (időpont: 2024. aug. 18.,
V 17:41):

> ***@***.**** requested changes on this pull request.
>
> This change should be in the systemd-initrd module.
> ------------------------------
>
> In modules.d/00systemd/module-setup.sh
> <https://github.com/dracut-ng/dracut-ng/pull/570#discussion_r1721005502>:
>
> > @@ -13,7 +13,7 @@ check() {
>
>  # called by dracut
>  depends() {
> -    return 0
> +    echo base
>
> @PrincessDoreena <https://github.com/PrincessDoreena> the suggestion from
> @jozzsi <https://github.com/jozzsi> makes sense for me. This change
> should be in the systemd-initrd dracut module instead. Would you be able
> to make this change in this PR or should someone else take it over from
> here ?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dracut-ng/dracut-ng/pull/570#pullrequestreview-2244346910>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AYOH5L2ZAYUOYGQMOUI4TPTZSC6DDAVCNFSM6AAAAABMG3BRQKVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDENBUGM2DMOJRGA>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-08-20 06:49 UTC, PrincessDoreena commented
Verbose log for the test failure on arch linux:
[test.log](https://github.com/user-attachments/files/16670217/test.log)

2024-08-20 13:51 UTC, LaszloGombos approved these changes
thanks. It has been a while since we've gained a new test. :-)

2024-08-21 13:34 UTC, merged