ci(Debian): make clang the default C compiler
dracut-ng/dracut-ng pull request #600
Opened 2024-08-24 00:53 UTC by jozzsi

Debian will allow to test clang both amd64 on and on arm64

## Checklist
- [ ] I have tested it locally
- [ ] I have reviewed and updated any documentation if relevant
- [ ] I am providing new code and test(s) for it

Fixes #

2024-08-24 12:45 UTC, LaszloGombos approved these changes
ok. this would fix https://github.com/dracut-ng/dracut-ng/issues/593

2024-08-24 13:02 UTC, Conan-Kudo requested changes
Debian builds officially with GCC and does not use Clang as the default compiler. If we want clang tests, we should make a separate test image for it.

2024-08-24 13:14 UTC, LaszloGombos commented
> Debian builds officially with GCC and does not use Clang as the default compiler. If we want clang tests, we should make a separate test image for it.

@bdrung what are your thoughts on this - specifically for the Ubuntu CI container ? 

Clang would only be used to build dracut source code as other packages are build from source. Any interest in clang from your perspective ?

2024-08-29 22:37 UTC, bdrung commented
Clang is not the default on Debian/Ubuntu. So there is probably no need to test clang both on Debian and Ubuntu. So having one *additional* test with clang on either Debian or Ubuntu would be fine.

2024-08-29 23:52 UTC, jozzsi commented
It seems there is not enough interest in clang to make it a default in any of the containers. There are certainly other ways to test clang - one of which is to test it outside of the upstream CI. Closing this PR for now.

2024-08-29 23:52 UTC, closed without merging